### ISSUE TITLE
How can i set up for PI2? = )

### ISSUE THREAD

**Issue by dcseng** [c-devine/OctoPrint-PanTilt-Script#1]

**Comment by dcseng** [comment]
I gotcha! It is the same for PI2! Works great! Great library! Great job!!
But now I'm trying to use on Salandora/OctoPrint-PanTilt plugin but nothing happens. 

Do you know why?

![notworking2](https://user-images.githubusercontent.com/4583389/32256827-97226294-be98-11e7-805b-bfda6f2bb0f3.PNG)
![notworking](https://user-images.githubusercontent.com/4583389/32256828-974cb80a-be98-11e7-8b8a-4dd4b0475386.PNG)

**Comment by c-devine** [comment]
Try the latest version.  The was a PR that was merged recently that might fix your issue.

**Comment by dcseng** [comment]
It's still not working. I've update Salandora plugin and it is not working yet.

I'm using 
OctoPrint version : 1.3.5
OctoPi version    : 0.14.0

Should I try an older version? How is your pantilt? working great? Which octoprint and octopi version are you using? Have you put on Path to Script: bash /home/pi/scripts/servopwm or just /home/pi/scripts/servopwm ?

Your bash script works like a charm. Thanks

**Comment by c-devine** [comment]
@camnop  I 'm using slightly different versions, so that might or might not be an issue.  You don't need to add bash to the beginning of the path - if you renamed the file - that's fine, just make sure the name is the same in the OctoPrint GUI.  I can think of a couple of things to try:
1)  is the script executable?  cd to the directory where the script is and type ` chmod a+x  ./servopwm.sh`  (or whatever you named the file).  After you do that, you should be able to run the script without the "bash" argument.  i.e. ` ./servopwm.sh 90 90`  If that works, that might be all you need to do!
2) are you logged in to OctoPrint as a user?  If not, you might need to be
3) did you re-start OctoPrint after uninstalling, and re-installing the new version?  Sometimes you need to restart OctoPrint to see the upgraded plugin
4) does the "set" button work?  Enter in some values into the Pan and Tilt text boxes in the Control tab and hit "set"
5) the last thing I can think of to look at are the logs.  Do you see anything in the file:  /home/pi/.octoprint/logs/octoprint.log

let me know what you find out!

**Comment by c-devine** [comment]
@camnop - Also, uninstall any of the other pan-tilt plugins like the OctoPrint-PanTilt-Nano or OctoPrint-PanTilt-ESP8266 plugin - if you installed them.  Right now if any of those are installed, the script will not be called.

**Comment by dcseng** [comment]
@c-devine thank you so much! It is working great now! 
You were right, my script was not executable so I typed `chmod a+x ./servopwm.sh `and now is working on PI2 OctoPrint version : 1.3.4  OctoPi version : 0.14.0

**Comment by c-devine** [comment]
@camnop Congratulations!  I think you are the first person to use the script (that I know of)!  I need to add the executable permissions to the instructions and add in Pi2.  Do you have a picture of your set up - I'd love to see it.
